[package]
name = "perfect-clear"
version = "0.1.0"
authors = ["wirelyre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
crossterm = "0.20.0"
parking_lot = "0.11.1"
rayon = "1.5.1"